// standard colours
export const white = '#fff'
export const black = '#000'
export const darkestGrey = '#333'
export const darkGrey = '#666'
export const green = '#0a0'
export const red = '#f55'
export const cyan = '#0ff'
export const grey = '#999'
export const lightGrey = '#ccc'
export const lighterGrey = '#eee'
export const transparent = 'transparent'